### ISSUE TITLE
Discussion of correctness of IClabel-python vs EEGLab

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-icalabel#5]
@mscheltienne reposting here as an issue to begin discussion again.

Quick update: our intern should have started on the 1st of March. But he did not yet get his work permit (mandatory in Switzerland), thus his start has been delayed and we hope he will be on board next week. 

-------

I finally took the time to test it! It looks very promising but seems to favor a lot 'Other'.
Am I correct in assuming that the classes outputted are in the order:

```
classes = ['Brain', 'Muscle', 'Eye', 'Heart', 'Line Noise', 'Channel Noise', 'Other']
```

I ran it on [this file](https://drive.google.com/file/d/1oqoRqLpYJVg65x-KzCmq8ezkXXJmGFtU/view?usp=sharing) quickly:

```
from matplotlib import pyplot as plt
import mne
import numpy as np

from mne_icalabel.ica_label import ica_eeg_features
from mne_icalabel.ica_net import run_iclabel

#%% Load
raw = mne.io.read_raw_fif('ica-test-raw.fif', preload=True)

#%% ICA
ica = mne.preprocessing.ICA(method='picard', max_iter='auto')
ica.fit(raw, picks='eeg')

#%% Features
features = ica_eeg_features(raw, ica)
topo = features[0].astype(np.float32)
psds = features[1].astype(np.float32)
autocorr = features[2].astype(np.float32)
labels = run_iclabel(topo, psds, autocorr)

classes = ['Brain', 'Muscle', 'Eye', 'Heart', 'Line Noise', 'Channel Noise', 
           'Other']

#%% Plot
f, axes = plt.subplots(1, 7, sharex=True, sharey=True, figsize=(20, 5))
for k, ax in enumerate(axes):
    ax.bar(np.arange(0, labels.shape[0]), labels[:, k])
    ax.set_title(classes[k])

for i, label in enumerate(labels):
    k = np.argmax(label)
    axes[k].bar(i, label[k], color='crimson')
    
f.tight_layout()

#%% ICA plots
ica.plot_components()
ica.plot_sources(raw)
```

![Screenshot 2022-03-04 at 16 40 40](https://user-images.githubusercontent.com/73893616/156793846-a85b2103-1c6d-4e3b-88fd-38703dd737ae.png)

Eye and heartbeat are correct. The last time we talked, you told me it failed at classifying even simple blinks, did you find what caused this?

_Originally posted by @mscheltienne in https://github.com/jacobf18/iclabel-python/issues/4#issuecomment-1059277016_

**Comment by adam2392** [comment]
> @mscheltienne reposting here as an issue to begin discussion again.
> Quick update: our intern should have started on the 1st of March. But he did not yet get his work permit (mandatory in Switzerland), thus his start has been delayed and we hope he will be on board next week.

Okay let us know when they are on board and we can schedule another time to chat.

> I finally took the time to test it! It looks very promising but seems to favor a lot 'Other'. Am I correct in assuming that the classes outputted are in the order:
> 
> ```
> classes = ['Brain', 'Muscle', 'Eye', 'Heart', 'Line Noise', 'Channel Noise', 'Other']
> ```

Yes this order is correct.

So last time @jacobf18 and I spoke, we identified this issue as well. There are three main components to the ICLabel pipeline:

- generate features from data (features)
- format the features to be fed into the network (formatting)
- actually run the data through the network (network)

So according to Jacob, he verified the network weights match that of EEGlab by running through various examples and confirming the outputs match numerically. However, a unit test that verifies this would be nice.

He also manually tested the formatting part.

We unit tested the generation of features on simulation data + raw loaded EEGLab data and all are matching numerically with EEGlab except for `rpsd`, which has a random component to it, which makes it difficult to match up w/ EEGlab.

I believe the differences in output can stem from any of these three parts, so we need to really be systematic in our testing of each of the three components of the pipeline against EEGLab in order to pinpoint exactly where are the differences. 

> Eye and heartbeat are correct. The last time we talked, you told me it failed at classifying even simple blinks, did you find what caused this?

Yes that was an incorrect specification of the sampling rate, which I fixed.

**Comment by mscheltienne** [comment]
Alright, I think the first task for Anand will be to run the network on Python and MATLAB, compare the outputs, familiarize himself with the code. He can also work on the unit test to verify that the network weights match and to verify the formatting part (if you don't beat him to it 😉). As you said, we have to be very systematic in our testing approach and we have to compare MATLAB and Python output at every stage. For `rpsd`, I wonder if there is a way to use the same random generator between both implementations, but let's put that one aside for now. 

At the moment, he is still waiting for his work permit, but he will pick up his laptop and a MATLAB license this week or at the beginning of next week.

**Comment by rnawaz** [comment]
Hello all, I am trying to install/import iclabel-mne but not successful. For a starting purpose I will try to execute the above example by @adam2392 but I am not sure what I am doing wrong. I tried to install mne-iclabel via pip install method mentioned in [here](https://github.com/jacobf18/iclabel-python) via following

(NOTE: i am working in colab that's why exclamation mark before pip command)
`!pip install --user -U https://api.github.com/repos/jacobf18/iclabel-python/zipball/main`

and get the message that it is successfully installed, see below

`Collecting https://api.github.com/repos/jacobf18/iclabel-python/zipball/main`
`  Downloading https://api.github.com/repos/jacobf18/iclabel-python/zipball/main`
`     - 122.7 MB 1.2 MB/s`
`Collecting mne>=0.24`
`  Downloading mne-0.24.1-py3-none-any.whl (7.4 MB)`
`     |████████████████████████████████| 7.4 MB 6.0 MB/s `
`Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.7/dist-packages (from mne-icalabel==0.1.dev0) (1.21.5)`
`Requirement already satisfied: scipy>=1.2.0 in /usr/local/lib/python3.7/dist-packages (from mne-icalabel==0.1.dev0) (1.4.1)`
`Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from mne-icalabel==0.1.dev0) (57.4.0)`
`Building wheels for collected packages: mne-icalabel`
`  Building wheel for mne-icalabel (setup.py) ... done`
`  Created wheel for mne-icalabel: filename=mne_icalabel-0.1.dev0-py2.py3-none-any.whl size=17612 sha256=6e077310f31de483cd83b50dcf6f88df93ba8f12a45b8cee05938a163e46a054`
`  Stored in directory: /tmp/pip-ephem-wheel-cache-be7s5va2/wheels/d4/00/98/7e59c6dea60d544087ce3d8d4067578061db5645b5538a1890`
`Successfully built mne-icalabel`
`Installing collected packages: mne, mne-icalabel`
`  WARNING: The script mne is installed in '/root/.local/bin' which is not on PATH.`
`  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.`
`Successfully installed mne-0.24.1 mne-icalabel-0.1.dev0`

but when I try to import the modules it says "ModuleNotFoundError: No module named 'mne_icalabel'". see below

`# import`
`from mne_icalabel.ica_label import ica_eeg_features`
`from mne_icalabel.ica_net import run_iclabel`

`ModuleNotFoundError                       Traceback (most recent call last)`
`<ipython-input-2-a755f923046f> in <module>()`
`      # import`
`----> from mne_icalabel.ica_label import ica_eeg_features`
`      from mne_icalabel.ica_net import run_iclabel`
`ModuleNotFoundError: No module named 'mne_icalabel'`
`---------------------------------------------------------------------------`
`NOTE: If your import is failing due to a missing package, you can`
`manually install dependencies using either !pip or !apt.`
`To view examples of installing some common dependencies, click the`
`"Open Examples" button below.`
`---------------------------------------------------------------------------`

Could you please let me know if my installation is not correct? Should there be another way to install mne-iclable? if yes, could you please update its procedure in the [main repo](https://github.com/jacobf18/iclabel-python) for future users.

any help would be much appreciated.
thanks
Rab

**Comment by adam2392** [comment]
@agramfort we are thinking of leveraging https://swipe4ica.github.io/#/ to build out an independent and bigger dataset to improve the ICLabel ported over from EEGLab.

I was thinking of having a hs student interested in working with me to contribute to this. 

- How easy is it to get access to this dataset from the web app?
- Is it ready for usage?

@mscheltienne in addition, you mentioned you have some external data. How difficult would it be to convert that data to BIDS and then we could have someone just run through all the data (i.e. this hs student) and label the IC components by hand? The main work on me/us would be we need to set up an almost-tutorial like ipython notebook for him to understand and sort of conceptualize what he's doing.

**Comment by agramfort** [comment]
>
> @agramfort <https://github.com/agramfort> we are thinking of leveraging
> https://swipe4ica.github.io/#/ to build out an independent and bigger
> dataset to improve the ICLabel ported over from EEGLab.
>
> I was thinking of having a hs student interested in working with me to
> contribute to this.
>
>    - How easy is it to get access to this dataset from the web app?
>
>
the EEG data is not public but the rendered images from the app are

the source code is here https://github.com/Swipe4ICA/swipe4ica.github.io


Message ID: ***@***.***>
>

**Comment by mscheltienne** [comment]
All our datasets have to be converted to a common format anyway, so let's go with BIDS. For the ANT Neuro and EGI datasets I can provide, I don't think it will be too much work to convert them to BIDS and to save the ICA decomposition in a BIDS format.

**Comment by adam2392** [comment]
Note for @adam2392 I need to push up the datafiles under `tests/data` and modify the .gitignore

**Comment by adam2392** [comment]
FYI: @mscheltienne and @anandsaini024 #11

**Comment by adam2392** [comment]
FYI @jacobf18 and I talked briefly today. He found an issue that he'll push up a PR for in the `autocorrelation` function.

**Comment by adam2392** [comment]
Now that this is "correct", should we release v0.1 on pypi? 

@mscheltienne

**Comment by mscheltienne** [comment]
I guess we can. Just one question, do we want to be backward compatible/use deprecation cycle from release 0.1 or can we keep some flexibility until a later release, e.g. when moved to `mne-tools`?

I'm thinking about the output of the main `label_components` function, currently, an array of shape `(n_components, n_classes)`, which is general and can be applied to any model; but might not be super user friendly, since you still have to figure out which component is in which class. Although I am not favorable either to a unique method, e.g. a hard threshold, to attribute a component to a class.

**Comment by adam2392** [comment]
Fair point. Let's finalize this API issue first before moving to v0.1.

Do you know where EEGLab documents the output order of the predicted class probabilities? I think the one I wrote in the examples is right, but it would be nice to double check this and have a reference to something.

Re how to output: 
- We can perhaps structure it like a sklearn Transformer, since it just transforms the raw data
- We can have a kwarg to either return predicted probabilities or the argmax and string labels?
- Other ideas?

**Comment by mscheltienne** [comment]
Does this count as documentation? It's probably where I found it the first time.. 
https://github.com/sccn/ICLabel/blob/e8abc99e0c371ff49eff115cf7955fafc7f7969a/iclabel.m#L60-L62

I'll have a look at the `Transformer`, I am not familiar with it.

**Comment by adam2392** [comment]
> Does this count as documentation? It's probably where I found it the first time.. 
> 
> https://github.com/sccn/ICLabel/blob/e8abc99e0c371ff49eff115cf7955fafc7f7969a/iclabel.m#L60-L62
> 
> 
> 
> I'll have a look at the `Transformer`, I am not familiar with it.
> 
> 

Ah yes that counts :p
