### ISSUE TITLE
Using it on Windows?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-icalabel#56]
Hello, has anyone here tried to use this package on Windows? I'm having a bit of trouble getting PyTorch to work on this platform via `conda-forge`, as there's currently not `conda-forge` package of PyTorch available: https://github.com/mne-tools/mne-installers/pull/123#issuecomment-1123310172

Just wanted to ask if anybody's got experience with this sort of issue?

**Comment by mscheltienne** [comment]
Yes, but I'm not using `conda` and I'm getting PyTorch from `pip`. Works like a charm :)

**Comment by hoechenberger** [comment]
How do you install Python?

**Comment by mscheltienne** [comment]
On windows, I grab the installer 64 bits here: https://www.python.org/downloads/release/python-3912/ (or a different version), install it for all users (I don't like installing in the user directories), and add the python directories to the system path (through the installer).
Then, since I'm using Spyder as IDE, I usually install it in the base environment with `py -m pip install spyder`. I create a virtual env for whatever project I'm working on with `py -m venv name`, and activate it with `name/Scripts/activate.bat`. 
Then, I install the dependencies I need for Spyder and plotting, e.g:

```
py -m pip install --upgrade pip setuptools wheel
py -m pip install spyder-kernels matplotlib pyqt5
py -m pip install numpy scipy mne torch
```

I'm doing very similarly on Linux or macOS where I install python via the package manage or homebrew and repeat the other steps. 

The beauty of python, you have 100 different ways of setting it up.. and messing it up! Someone recently shared this nice illustration recently:

![python_environment](https://user-images.githubusercontent.com/73893616/167816683-b3e503c2-a7d5-4b4b-a6cb-a4fc7dc6f61d.png)

**Comment by hoechenberger** [comment]
The comic is outdated, macOS doesn't ship with system Python anymore :)

**Comment by mscheltienne** [comment]
I'm still running 11.6 Big Sur, too scared to update :)
Glad to know that they finally got rid of this 2.7 default version!

**Comment by adam2392** [comment]
I haven't used a Windows computer in over 5-10(?) years now, so unfortunately I cannot help :p

**Comment by hoechenberger** [comment]
Yes, same … But I suppose I should get one specifically for this kind of stuff

**Comment by jacobf18** [comment]
@hoechenberger I'm not using a windows machine, but if you want to try installing PyTorch on your own and using the source code from git directly, the PyTorch page describes how to install it on windows: https://pytorch.org/get-started/locally/.

**Comment by anbara** [comment]
Hello, I report that my windows machine can run mne-icalabel on micromamba environment.
The solution is simply to add a pytorch channel.
```shell
micromamba create -n hoge python=3.10 mne=1.3 mne-icalabel=0.4 -c conda-forge -c pytorch
```

Additionally, the [installation document (Installation via Cond)](https://mne.tools/mne-icalabel/stable/install.html#installation-via-conda) includes wrong information. 
This command does not install mne-icalabel on windows.
I think you had better update the documentation.

This project is very great for me. Thanks to all contributors. :smile:

**Comment by mscheltienne** [comment]
Hello, thanks for the report. I will try to fix the documentation for conda.

**Comment by hoechenberger** [comment]
cc @larsoner, we should try that for our Windows standalone MNE installers

**Comment by jacobf18** [comment]
@hoechenberger @mscheltienne I opened a pull request that adds support for ONNX on top of PyTorch. I have not tested it personally on windows (outside the GitHub unit-tests), but there is a conda-forge link to the `onnxruntime` library. We can add additional functionality to choose which underlying library to use when installing mne-icalable if installing PyTorch is a problem.

**Comment by mscheltienne** [comment]
Closing as this should now be fixed with the ONNX backend and with MNE-installers.

**Comment by hoechenberger** [comment]
Yes, thank you!
